<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit55f04c10766d9d6a35d28a6ee1894d01
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Carbon_Fields\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Carbon_Fields\\' => 
        array (
            0 => __DIR__ . '/..' . '/htmlburger/carbon-fields/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit55f04c10766d9d6a35d28a6ee1894d01::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit55f04c10766d9d6a35d28a6ee1894d01::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit55f04c10766d9d6a35d28a6ee1894d01::$classMap;

        }, null, ClassLoader::class);
    }
}
